<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Paul Kerl" />

<meta name="date" content="2017-12-17" />

<title>RepData_PeerAssessment1</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<link href="PA1_template_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="PA1_template_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">RepData_PeerAssessment1</h1>
<h4 class="author"><em>Paul Kerl</em></h4>
<h4 class="date"><em>12/17/2017</em></h4>

</div>


<pre class="r"><code># set up working directory
setwd(&#39;/Users/pyk/Desktop/RepData_PeerAssessment1-PYK&#39;)</code></pre>
<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<p>Show any code that is needed to:</p>
<ol style="list-style-type: decimal">
<li><p>Load the data (i.e. read.csv())</p></li>
<li><p>Process/transform the data (if necessary) into a format suitable for your analysis</p></li>
</ol>
<pre class="r"><code># load data
data_row &lt;- read.csv(&#39;activity.csv&#39;)

# remove NA in data
data &lt;- data_row[ with (data_row, { !(is.na(steps)) } ), ]

# print out first 20 rows
head(data,20)</code></pre>
<pre><code>##     steps       date interval
## 289     0 2012-10-02        0
## 290     0 2012-10-02        5
## 291     0 2012-10-02       10
## 292     0 2012-10-02       15
## 293     0 2012-10-02       20
## 294     0 2012-10-02       25
## 295     0 2012-10-02       30
## 296     0 2012-10-02       35
## 297     0 2012-10-02       40
## 298     0 2012-10-02       45
## 299     0 2012-10-02       50
## 300     0 2012-10-02       55
## 301     0 2012-10-02      100
## 302     0 2012-10-02      105
## 303     0 2012-10-02      110
## 304     0 2012-10-02      115
## 305     0 2012-10-02      120
## 306     0 2012-10-02      125
## 307     0 2012-10-02      130
## 308     0 2012-10-02      135</code></pre>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is mean total number of steps taken per day?</h2>
<p>For this part of the assignment, you can ignore the missing values in the dataset.</p>
<ol style="list-style-type: decimal">
<li><p>Make a histogram of the total number of steps taken each day</p></li>
<li><p>Calculate and report the mean and median total number of steps taken per day</p></li>
</ol>
<pre class="r"><code>#steps by day
by_day &lt;- group_by(data, date)
steps_by_day &lt;- summarise(by_day, total = sum(steps))</code></pre>
<pre class="r"><code>#histogram
qplot(steps_by_day$total, geom=&quot;histogram&quot;, bins=20,  main = &quot;Number of steps per day&quot;, 
        xlab = &quot;Total Steps per Day (binned)&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/hist_of_steps_by_day-1.png" /><!-- --></p>
<pre class="r"><code>#mean and median
summary(steps_by_day)</code></pre>
<pre><code>##          date        total      
##  2012-10-02: 1   Min.   :   41  
##  2012-10-03: 1   1st Qu.: 8841  
##  2012-10-04: 1   Median :10765  
##  2012-10-05: 1   Mean   :10766  
##  2012-10-06: 1   3rd Qu.:13294  
##  2012-10-07: 1   Max.   :21194  
##  (Other)   :47</code></pre>
<p>Mean: 10766 Median: 10765</p>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<ol style="list-style-type: decimal">
<li><p>Make a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)</p></li>
<li><p>Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?</p></li>
</ol>
<pre class="r"><code># preprocessing data for plot
steps_by_interval &lt;- aggregate(steps ~ interval, data, mean)

# create a time series plot 
plot(steps_by_interval$interval, steps_by_interval$steps, type=&#39;l&#39;, 
     main=&quot;Average number of steps across days&quot;, xlab=&quot;Interval&quot;, 
     ylab=&quot;Average steps per day&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/plot_avg_steps_day-1.png" /><!-- --></p>
<pre class="r"><code># find row with max of steps
max_steps_row &lt;- which.max(steps_by_interval$steps)

# find interval with this max
steps_by_interval[max_steps_row, ]</code></pre>
<pre><code>##     interval    steps
## 104      835 206.1698</code></pre>
<p>The period with the max avg # of steps was 835 which had 206.17 steps on average</p>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<p>Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.</p>
<ol style="list-style-type: decimal">
<li><p>Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)</p></li>
<li><p>Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.</p></li>
<li><p>Create a new dataset that is equal to the original dataset but with the missing data filled in.</p></li>
<li><p>Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?</p></li>
</ol>
<pre class="r"><code># find missing data
sum(is.na(data_row))</code></pre>
<pre><code>## [1] 2304</code></pre>
<p>2304 missing data points</p>
<p>Data below is imputed using the mean value</p>
<pre class="r"><code># find missing data

data_imputed &lt;- data_row
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value &lt;- data_imputed$interval[i]
    steps_value &lt;- steps_by_interval[
      steps_by_interval$interval == interval_value,]
    data_imputed$steps[i] &lt;- steps_value$steps
  }
}</code></pre>
<pre class="r"><code># calculate  total number of steps taken each day
df_imputed_steps_by_day &lt;- aggregate(steps ~ date, data_imputed, sum)
head(df_imputed_steps_by_day)</code></pre>
<pre><code>##         date    steps
## 1 2012-10-01 10766.19
## 2 2012-10-02   126.00
## 3 2012-10-03 11352.00
## 4 2012-10-04 12116.00
## 5 2012-10-05 13294.00
## 6 2012-10-06 15420.00</code></pre>
<pre class="r"><code># create histogram
qplot(df_imputed_steps_by_day$steps, geom=&quot;histogram&quot;, bins=20,  main = &quot;Number of steps per day (imputed data)&quot;, xlab = &quot;Total Steps per Day (binned)&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/create_second_histogram-1.png" /><!-- --></p>
<pre class="r"><code># get mean and median of imputed data
mean(df_imputed_steps_by_day$steps)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code>median(df_imputed_steps_by_day$steps)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code># get mean and median of data without NA&#39;s
mean(steps_by_day$total)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code>median(steps_by_day$total)</code></pre>
<pre><code>## [1] 10765</code></pre>
<p>Mean values stayed the same (due to replacement of NA by mean values), but the median slightly changed due to the imputation using the mean 5-min values. Median is now unsurprisingly the mean due to the frequency of replacement.</p>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
<p>For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.</p>
<ol style="list-style-type: decimal">
<li><p>Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.</p></li>
<li><p>Make a panel plot containing a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). The plot should look something like the following, which was created using simulated data:</p></li>
</ol>
<pre class="r"><code>#get the type of day -- using weekdays
data_imputed[&#39;type_of_day&#39;] &lt;- weekdays(as.Date(data_imputed$date))

#label as weekend
data_imputed$type_of_day[data_imputed$type_of_day  %in% c(&#39;Saturday&#39;,&#39;Sunday&#39;) ] &lt;- &quot;weekend&quot;

#label as weekday
data_imputed$type_of_day[data_imputed$type_of_day != &quot;weekend&quot;] &lt;- &quot;weekday&quot;

# convert type_of_day from character to factor
data_imputed$type_of_day &lt;- as.factor(data_imputed$type_of_day)

# calculate average steps by interval across all days
df_imputed_steps_by_interval &lt;- aggregate(steps ~ interval + type_of_day, data_imputed, mean)</code></pre>
<pre class="r"><code># create a plot using the weekday vs. weekend data
qplot(interval, 
      steps, 
      data = df_imputed_steps_by_interval, 
      type = &#39;l&#39;, 
      geom=c(&quot;line&quot;),
      xlab = &quot;Interval&quot;, 
      ylab = &quot;Number of steps&quot;, 
      main = &quot;&quot;) +
  facet_wrap(~ type_of_day, ncol = 1)</code></pre>
<pre><code>## Warning: Ignoring unknown parameters: type</code></pre>
<p><img src="PA1_template_files/figure-html/plot_weekday_vs_weekend-1.png" /><!-- --></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
